base_url = "https://limeleaf.net"
title = "Limeleaf Worker Collective | Rust and Go Development Experts"
description = "We are a worker-owned cooperative that helps teams build fast, reliable, maintainable software using modern programming languages."

generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
  { name = "tags", feed = false },
  { name = "areas", feed = false, render = false },
]
 
[markdown]
highlight_code = true
highlight_theme = "axar"

[extra]
copyright = "Limeleaf Worker Collective, LLC"
